### ISSUE TITLE
Update for NC22 missing

### ISSUE THREAD

**Issue by liquidat** [nextcloud/user_external#179] opened 2021-07-13 21:03 UTC
### Steps to reproduce

1. Install Nextcloud 22
2. Try to install this app

### Expected behaviour

The app should work.

### Actual behaviour

The app doesn't work - it is not compatible with nc 22.

### Affected Authentication backend

General problem

### Server configuration

**Nextcloud version:** 22

**Updated from an older Nextcloud/ownCloud or fresh install:** both

**Comment by Glandos** [comment] 2021-07-26 12:29
Do you have any log to share?

**Comment by liquidat** [comment] 2021-07-26 21:42
@Glandos It is hardcoded in the app's `info.xml`:
https://github.com/nextcloud/user_external/blob/b18ddbb091430b5c1db2983aca735159ba97dc05/appinfo/info.xml#L35

**Comment by prismopensource** [comment] 2021-07-27 08:21
Will it work if you manually edit the XML?

**Comment by liquidat** [comment] 2021-07-27 08:57
It did, at least as far as I can tell. But I have a very limited use case, just a few exciting users via IMAP. I haven't tested things like new users yet, otherwise I would have created a PR.

**Comment by spiffyguy** [comment] 2021-08-18 18:51
Hi there,

I just updated as well and enabled the "untested app" in Nextcloud 22.  While it works with IMAP authentication to login.  I can't seem to login with the Nextcloud App to sync files, have desktop notifications.

I am on a Mac but I am pretty sure this works the same way with Windows as well.  I click on the tray icon in the menu bar. and then click "Log In" and it does open the browser to my nextcloud instance, asking for me to login.  I login successfully and it takes me to the page that says "You are logged in.  You may now close the browser."  (Something like that) but it never actually logs in on the app itself.  My name shows up, but nothing else and only gives me the option to log in.  It won't ever switch to being logged in.

![image](https://user-images.githubusercontent.com/4824923/129952417-94e81dba-0ad0-4ef7-841a-5229c3f607e9.png)

![image](https://user-images.githubusercontent.com/4824923/129955269-47aac5e2-157f-44d4-8cb9-afecd86e2da0.png)

Anyone else experience this at all?

I have updated the client to the latest 3.3.1.  But I already was on the latest client version before upgrading to Nextcloud 22 and then force-activating this app.

- Matt

**Comment by violoncelloCH** [comment] 2021-09-05 12:56
new release compatible with Nextcloud Hub 22 is on it's way and will be released soonish: #184 

@spiffyguy this doesn't seam related at all and I can't reproduce your issue. Please open a separate issue with further details or better check the desktop client repo for similar issues: https://github.com/nextcloud/desktop/issues

**Closed** 2021-09-07 11:42 UTC
Labels: bug, 0. Needs triage
