### ISSUE TITLE
Update to NextCloud 22.1.1 needed

### ISSUE THREAD

**Issue by arsounet** [nextcloud/user_external#182] opened 2021-08-31 11:11 UTC
The External user authentication needs to be updated for NextCloud 22.1.1.

Maybe it's not need in code but give a look at the NextCloud support.

![image](https://user-images.githubusercontent.com/758451/131492912-f26c0998-f723-4d21-9001-5ee0af7c885d.png)

Big thanks

**Comment by violoncelloCH** [comment] 2021-09-01 09:33
closing as duplicate of #179

**Closed by violoncelloCH** 2021-09-01 09:33 UTC
Labels: enhancement, 0. Needs triage
