### ISSUE TITLE
Nextcloud-15.0 & user_external-0.4

### ISSUE THREAD

**Issue by Thom1b** [nextcloud/user_external#4] opened 2018-12-11 08:56 UTC
### Affected apps
user_external

### Steps to reproduce
Upgrade from Nextcloud-14.0.4 to Nextcloud-15.0

### Expected behaviour
user_external should work

### Actual behaviour
user_external can't be enable because version 0.4, which is embebbed, in nc-15.0 doesn't support nc-15.0.
"apps/user_external/appinfo/info.xml":
`<nextcloud min-version="13" max-version="14" />`

I tried do simply modify max-version to 15 and it seems working (with IMAP authentification in my case).

**Comment by violoncelloCH** [comment] 2018-12-21 17:32
thank you for reporting
duplicate of nextcloud/server#12506 
also we probably unbundle user_external and update it independently via appstore (#22) so it will be fixed with NC 15.0.1 or as soon as we have got the update via appstore ready

**Closed by violoncelloCH** 2018-12-21 17:32 UTC
