### ISSUE TITLE
Incompatible with Nextcloud 28.0.3

### ISSUE THREAD

**Issue by peter4200** [nextcloud/user_external#245] opened 2024-02-29 18:09 UTC
### Steps to reproduce
1. Nextcloud prior to version 28.0.3
2. Goto Administration Setting
3. Check Update section

### Expected behaviour
No warnings 

### Actual behaviour
Warning about incompatible

### Affected Authentication backend
IMAP

### Server configuration

**User External App version:** (see Nextcloud apps page)

**Operating system:**
Ubuntu 22.04, fully updated

**Web server:**
Apache 2.4.52

**Database:**
Mariadb 15.1

**PHP version:**
8.1.2.

**Nextcloud version:** (see Nextcloud admin page)
27.1.7

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from previous version (27.1.6)

**Where did you install Nextcloud from:**
Nextcloud homepage

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here.
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by prismopensource** [comment] 2024-03-04 14:54
Seems like a duplicate of [Nextcloud 28 support #240](https://github.com/nextcloud/user_external/issues/240)

**Comment by Thom1b** [comment] 2024-03-16 05:51
Hi,
I just want to thanks all devs of this app. I used it since… maybe 10 years. It's  a great app. Now I migrate all my imap accounts to ldap, it works fine!
Thanks again ;)

**Comment by kng-seb** [comment] 2024-03-19 21:13
Unfortunately the release is still missing - it would be great if someone could draft a new release!

**Closed** 2024-04-02 08:29 UTC
Labels: bug, 0. Needs triage
